# Generated by Django 5.0.4 on 2024-07-29 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_relatorio_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')]),
            preserve_default=False,
        ),
    ]
