# Generated by Django 5.0.4 on 2024-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconhecimentoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reconheceu', models.BooleanField(default=False)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('registro_acesso', models.CharField(max_length=100)),
            ],
        ),
    ]
