# Generated by Django 5.0.4 on 2024-07-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconhecimento_facial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconhecimentofacial',
            name='foto',
        ),
    ]
